//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.ServiceReferenceEventLog {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceEventLog.WebServiceEventLogSoap")]
    public interface WebServiceEventLogSoap {
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveXML", ReplyAction="*")]
        UI.ServiceReferenceEventLog.SaveXMLResponse SaveXML(UI.ServiceReferenceEventLog.SaveXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveXML", ReplyAction="*")]
        System.Threading.Tasks.Task<UI.ServiceReferenceEventLog.SaveXMLResponse> SaveXMLAsync(UI.ServiceReferenceEventLog.SaveXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveXML", Namespace="http://tempuri.org/", Order=0)]
        public UI.ServiceReferenceEventLog.SaveXMLRequestBody Body;
        
        public SaveXMLRequest() {
        }
        
        public SaveXMLRequest(UI.ServiceReferenceEventLog.SaveXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public SaveXMLRequestBody() {
        }
        
        public SaveXMLRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public UI.ServiceReferenceEventLog.SaveXMLResponseBody Body;
        
        public SaveXMLResponse() {
        }
        
        public SaveXMLResponse(UI.ServiceReferenceEventLog.SaveXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveXMLResponseBody {
        
        public SaveXMLResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceEventLogSoapChannel : UI.ServiceReferenceEventLog.WebServiceEventLogSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceEventLogSoapClient : System.ServiceModel.ClientBase<UI.ServiceReferenceEventLog.WebServiceEventLogSoap>, UI.ServiceReferenceEventLog.WebServiceEventLogSoap {
        
        public WebServiceEventLogSoapClient() {
        }
        
        public WebServiceEventLogSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceEventLogSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEventLogSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEventLogSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UI.ServiceReferenceEventLog.SaveXMLResponse UI.ServiceReferenceEventLog.WebServiceEventLogSoap.SaveXML(UI.ServiceReferenceEventLog.SaveXMLRequest request) {
            return base.Channel.SaveXML(request);
        }
        
        public void SaveXML(string xml) {
            UI.ServiceReferenceEventLog.SaveXMLRequest inValue = new UI.ServiceReferenceEventLog.SaveXMLRequest();
            inValue.Body = new UI.ServiceReferenceEventLog.SaveXMLRequestBody();
            inValue.Body.xml = xml;
            UI.ServiceReferenceEventLog.SaveXMLResponse retVal = ((UI.ServiceReferenceEventLog.WebServiceEventLogSoap)(this)).SaveXML(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UI.ServiceReferenceEventLog.SaveXMLResponse> UI.ServiceReferenceEventLog.WebServiceEventLogSoap.SaveXMLAsync(UI.ServiceReferenceEventLog.SaveXMLRequest request) {
            return base.Channel.SaveXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<UI.ServiceReferenceEventLog.SaveXMLResponse> SaveXMLAsync(string xml) {
            UI.ServiceReferenceEventLog.SaveXMLRequest inValue = new UI.ServiceReferenceEventLog.SaveXMLRequest();
            inValue.Body = new UI.ServiceReferenceEventLog.SaveXMLRequestBody();
            inValue.Body.xml = xml;
            return ((UI.ServiceReferenceEventLog.WebServiceEventLogSoap)(this)).SaveXMLAsync(inValue);
        }
    }
}
